name = "React Router"
roles = ["frontend", "backend"]
webhooks_path = "/webhooks/app/uninstalled"

[commands]
predev = "npx prisma generate && npx prisma db push"
dev = "npx prisma generate && npx prisma db push && npm exec react-router dev"


